stages:
  - migrate
  - seed

variables:
  AWS_REGION: ap-northeast-1
  TF_ENV: development
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

migrate:database:
  stage: migrate
  image: alpine:latest
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    AWS_DEFAULT_REGION: ap-northeast-1
  before_script:
    - sleep 15
    - apk add --no-cache make docker aws-cli python3 postgresql-client curl unzip jq bash
    - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    - unzip terraform_1.5.7_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - chmod +x /usr/local/bin/terraform
    - docker info
    - 'echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:+SET}"'
    - 'echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:+SET}"'
    - 'echo "AWS_REGION: $AWS_REGION"'
    - aws sts get-caller-identity
    - ls -la scripts/terraform/
    - chmod +x scripts/terraform/*.sh
  script:
    - bash scripts/terraform/aws-migrate-ci.sh $TF_ENV
  only:
    - develop
    - main
    - feature/gitlab-ci-clean-v2
  when: manual
  timeout: 45m

seed:test-users:
  stage: seed
  image: alpine:latest
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    AWS_DEFAULT_REGION: ap-northeast-1
  before_script:
    - sleep 15
    - apk add --no-cache make docker aws-cli python3 postgresql-client curl unzip jq bash
    - docker info
    - 'echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:+SET}"'
    - 'echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:+SET}"'
    - 'echo "AWS_REGION: $AWS_REGION"'
    - aws sts get-caller-identity
    - ls -la scripts/terraform/
    - chmod +x scripts/terraform/*.sh
  script:
    - bash scripts/terraform/aws-seed-user.sh $TF_ENV
  dependencies:
    - migrate:database
  only:
    - develop
    - main
    - feature/gitlab-ci-clean-v2
  when: manual
  timeout: 30m