# テストケース管理システム - テスト環境設定ファイル
#
# このファイルはテスト実行時の設定をオーバーライドするために使用されます。
# 現在は空のファイルですが、テスト特有の設定を追加する場合に使用します。
# 例えば:
# - インメモリデータベースの設定
# - モックサービスの設定
# - 短いタイムアウト値
# - テスト用の認証設定
#
# テスト実行時には、環境変数 GO_ENV=test を設定することで、
# このファイルが優先的に読み込まれます。