package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
)

// AdminData は管理者専用データを返すリゾルバー
func (r *queryResolver) AdminData(ctx context.Context) (string, error) {
	return "これは管理者(Admin)のみがアクセスできるデータです", nil
}

// ManagerData は管理者専用データを返すリゾルバー
func (r *queryResolver) ManagerData(ctx context.Context) (string, error) {
	return "これは管理者(Manager)のみがアクセスできるデータです", nil
}

// TesterData はテスター専用データを返すリゾルバー
func (r *queryResolver) TesterData(ctx context.Context) (string, error) {
	return "これはテスター(Tester)のみがアクセスできるデータです", nil
}
